name: Deploy Dino Game

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install pygbag
        run: pip install pygbag

      - name: Build with pygbag
        run: pygbag --build main.py
 
      - name: Debug build output
        run: ls -R ./build

      - name: Verify build output
        run: ls -la ./build/web

      - name: Disable Jekyll
        run: echo "" > ./build/web/.nojekyll


      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
